export const reducerCases = {
    SET_ROW: 'SET_ROW',
    SET_COUNTRY: 'SET_COUNTRY',




    SET_TOKEN: 'SET_TOKEN',
    SET_CARD: 'SET_CARD',

    SET_IS_EVENT_ADD: 'SET_IS_EVENT_ADD',
    SET_IS_EVENT_EDIT: 'SET_IS_EVENT_EDIT',
    SET_IS_EVENT_HOVER: 'SET_IS_EVENT_HOVER',
    SET_EVENT_ID: 'SET_EVENT_ID',
    SET_EVENT_DATE: 'SET_EVENT_DATE',
    SET_EVENT_TITLE: 'SET_EVENT_TITLE',
    SET_EVENT_NOTE: 'SET_EVENT_NOTE',
    SET_EVENT_PRIO: 'SET_EVENT_PRIO',
    SET_EVENT_FILTER_MONTH: 'SET_EVENT_FILTER_MONTH',
    SET_EVENT_FILTER_YEAR: 'SET_EVENT_FILTER_YEAR',

    // Task 3
    SET_TIMELINE_DATA: 'SET_TIMELINE_DATA',
    
    SET_MACHINE_FILTER_SEARCH: 'SET_MACHINE_FILTER_SEARCH',
    SET_MACHINE_FILTER_SITES: 'SET_MACHINE_FILTER_SITES',
    SET_MACHINE_FILTER_PLANTS: 'SET_MACHINE_FILTER_PLANTS',
    SET_MACHINE_FILTER_DEPARTMENTS: 'SET_MACHINE_FILTER_DEPARTMENTS',
    SET_MACHINE_FILTER_WORKCENTERS: 'SET_MACHINE_FILTER_WORKCENTERS',
    SET_MACHINE_FILTER_WORKSTATIONS: 'SET_MACHINE_FILTER_WORKSTATIONS',
    SET_MACHINE_FILTER_ASSETS: 'SET_MACHINE_FILTER_ASSETS',
    SET_MACHINE_FILTER_DATE: 'SET_MACHINE_FILTER_DATE',
}